image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  POETRY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/poetry"
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"

cache:
  paths:
    - .cache/pip
    - .cache/poetry
    - .cache/pre-commit

before_script:
  - python -VV
  - pip install poetry pre-commit
  - poetry install --sync

pre_commit:
  script:
    - poetry run pre-commit run --all-files
  coverage: '/Total coverage: \d+\.\d+%/'
  artifacts:
    paths:
      - htmlcov

test:
  script:
    - poetry run pytest "tests/"
      -n 4
      --dist worksteal
      --reruns 3
      --verbose
      --cov=aws_lambda_python_packager
      --pyargs "aws_lambda_python_packager"
      --cov-report=html --cov-report=term --cov-report=xml

build:
  needs:
    - pre_commit
    - test
  script:
    - poetry build
  artifacts:
    paths:
      - dist

publish:
  needs:
    - build
  script:
    - rm -rf dist
    - poetry build
    - pip install twine
    - twine upload dist/*.whl
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/
